# _config.yml
title: CLI og kodding hjemmeside
description: Litt introduksjon til CLI, script og ulike programspråk
markdown: gfm
show_downloads: true
# Hente inn css fra leap-day som gir en form for TOC og navigering
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# theme: jekyll-theme-minimal
# theme: jekyll-theme-leap-day
# theme: jekyll-theme-hacker
# markdown: GFM