# _config.yml
theme: jekyll-theme-hacking
title: CLI og kodding hjemmeside
description: Litt introduksjon til CLI, script og ulike programspråk
markdown: gfm
show_downloads: true

# theme: jekyll-theme-minimal
# theme: jekyll-theme-leap-day
# markdown: GFM